[libraries]

#jackson-core = "com.fasterxml.jackson.core:jackson-core:2.13.1"
#implementation("com.fasterxml.jackson.core:jackson-databind:2.13.1")
#implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.1")
#implementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.1")
