package org.cardanofoundation.lob.app.accounting_reporting_core.domain.core;

public enum TransactionViolationCode {

    DOCUMENT_MUST_BE_PRESENT,
    TX_CANNOT_BE_ALTERED,
    ACCOUNT_CODE_CREDIT_IS_EMPTY,
    ACCOUNT_CODE_DEBIT_IS_EMPTY,
    TX_TECHNICAL_FAILURE,
    LCY_BALANCE_MUST_BE_ZERO,
    FCY_BALANCE_MUST_BE_ZERO,
    AMOUNT_LCY_IS_ZERO,
    AMOUNT_FCY_IS_ZERO,
    ALL_TX_ITEMS_ERASED,
    VAT_DATA_NOT_FOUND,
    CORE_CURRENCY_NOT_FOUND,
    CURRENCY_DATA_NOT_FOUND,
    COST_CENTER_DATA_NOT_FOUND,
    PROJECT_DATA_NOT_FOUND,
    CHART_OF_ACCOUNT_NOT_FOUND,
    EVENT_DATA_NOT_FOUND,
    ORGANISATION_DATA_NOT_FOUND,
    JOURNAL_DUMMY_ACCOUNT_MISSING,
    TX_VERSION_CONFLICT_TX_NOT_MODIFIABLE

}
