name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Test
        run: |
          ./gradlew clean test jacocoTestReport

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          ./gradlew sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=cardano-foundation \
          -Dsonar.projectKey=cardano-foundation_cf-lob-platform \
          -Dsonar.branch.name=${{ github.head_ref }}
